- name: DeepSource Test Coverage Action
  # You may pin to the exact commit or the version.
  # uses: deepsourcelabs/test-coverage-action@5dd75fd448df1d437bc9d658db0ee7d67a915c9f
  uses: deepsourcelabs/test-coverage-action@v1.0.0
  with:
    # Programming language shortcode for which coverage is reported. Allowed values are — python, go
    key: 
    # Path to the coverage data file. e.g. ./coverage.xml
    coverage-file: 
    # DeepSource DSN of this repository. It is available under Settings → Reporting tab of the repository page on DeepSource.
    dsn: 
    # Should the CI build fail if there is an error while uploading the report to DeepSource? Allowed values are — true, false
    fail-ci-on-error: # optional
